### ISSUE TITLE
如何使用al多平台接受文件？

### ISSUE THREAD

**Issue by Agnes4m** [nonebot/plugin-alconna#62]
翻阅文档demo并没有给出如果是zip文件的多接受方式，而文档提到了支持多种适配器的文件元素，是否可以给出示例代码，使得可以多平台接受到具体上传的文件？

**Comment by RF-Tar-Railt** [comment]
两种情况
一种使用on_message：
```python
from nonebot_plugin_alconna import UniMsg, File

matcher = on_message()

@matcher.handle()
async def _(msg: UniMsg):
    if not msg.has(File):
        matcher.skip()
    files = msg[File]  # list[File]
```

一种用特殊的Alconna:
```python
from nonebot_plugin_alconna import Alconna, File, on_alconna


matcher = on_alconna(Alconna(File))
```

**Comment by Agnes4m** [comment]
那么，如果适配器允许的情况下，如何上传文件呢？

**Comment by KomoriDev** [comment]
> 那么，如果适配器允许的情况下，如何上传文件呢？

使用 `UniMessage.file`
https://github.com/nonebot/plugin-alconna/blob/91b36f2d4a0df8cc79cf51813bd69d44d4bb71c6/src/nonebot_plugin_alconna/uniseg/message.py#L277-L299
