### ISSUE TITLE
[Bug] 同一个handler被同一个响应器assign不同path后无法响应

### ISSUE THREAD

**Issue by wangyw15** [nonebot/plugin-alconna#76]
## 请确认：

* [x] 问题的标题明确
* [x] 我翻阅过其他的issue并且找不到类似的问题
* [x] 我已经阅读了[相关文档](https://nonebot.dev/docs/next/best-practice/alconna/) 并仍然认为这是一个Bug

# Bug

## 问题
同一个`handler`被同一个响应器`assign`不同`path`后无法响应

问题发生在 https://github.com/nonebot/plugin-alconna/commit/61e7ce87365c4fbc48382c2980034d33f7e97112 这一commit后

回退到上一个commit则可正常使用

## 如何复现
```python
from nonebot_plugin_alconna import (
    on_alconna,
    Alconna,
    Subcommand,
)

command = on_alconna(Alconna(
    "test",
    Subcommand("s1"),
    Subcommand("s2"),
), block=True)

@command.assign("s1")
@command.assign("s2")
async def _():
    await command.finish("hello")
```

此时`test s1`与`test s2`均无法响应

如果删除`@command_handler.assign("s2")`一行，`test s1`可响应

## 预期行为
`test s1`与`test s2`均可响应消息

## 使用环境:
- Python 版本: 3.12.7
- Nonebot2 版本: 2.3.3
- Alconna 版本: 0.52.0

## 日志/截图

![Image](https://github.com/user-attachments/assets/cac9bff8-0a05-4f00-8033-4b4397f73933)

**Comment by RF-Tar-Railt** [comment]
0.52.0 版本中以后认为该功能为特性了

**Comment by wangyw15** [comment]
目前除了回退版本，还有可以恢复旧版本行为的方式吗？

**Comment by RF-Tar-Railt** [comment]
目前不鼓励对于不同path使用同一个handler的行为。

既然不关注path的差异，那为什么不直接使用`.handle()` 然后注入 `arp: Arparma` 再使用 `if arp.find(path1) or arp.find(path2)`呢

**Comment by wangyw15** [comment]
本意是通过多个`assign`，对不同path进行一部分代码复用。经过提示想到确实可以使用`handle`来代替

感谢
